// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLogs() {
  return window['go']['app']['App']['FetchLogs']();
}

export function StartService() {
  return window['go']['app']['App']['StartService']();
}

export function StopService() {
  return window['go']['app']['App']['StopService']();
}
